
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EncuestasOrt
{

using System;
    using System.Collections.Generic;
    
public partial class EncuestaRealizada
{

    public EncuestaRealizada()
    {

        this.EncuestaRespuesta = new HashSet<EncuestaRespuesta>();

    }


    public int Id { get; set; }

    public int EncuestaID { get; set; }

    public System.DateTime FechaHora { get; set; }



    public virtual Encuesta Encuesta { get; set; }

    public virtual ICollection<EncuestaRespuesta> EncuestaRespuesta { get; set; }

}

}
