//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestasOrt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EncuestasContainer : DbContext
    {
        public EncuestasContainer()
            : base("name=EncuestasContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Encuesta> Encuesta { get; set; }
        public virtual DbSet<EncuestaPregunta> EncuestaPregunta { get; set; }
        public virtual DbSet<EncuestaRespuesta> EncuestaRespuesta { get; set; }
        public virtual DbSet<Materia> Materia { get; set; }
        public virtual DbSet<Opcion> Opcion { get; set; }
        public virtual DbSet<Pregunta> Pregunta { get; set; }
        public virtual DbSet<Carrera> Carrera { get; set; }
        public virtual DbSet<EncuestaRealizada> EncuestaRealizada { get; set; }
        public virtual DbSet<Tematica> Tematica { get; set; }
    }
}
