//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestasOrt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materia
    {
        public Materia()
        {
            this.Encuesta = new HashSet<Encuesta>();
            this.Pregunta = new HashSet<Pregunta>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> TematicaID { get; set; }
    
        public virtual ICollection<Encuesta> Encuesta { get; set; }
        public virtual ICollection<Pregunta> Pregunta { get; set; }
        public virtual Tematica Tematica { get; set; }
    }
}
