
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EncuestasOrt
{

using System;
    using System.Collections.Generic;
    
public partial class Opcion
{

    public Opcion()
    {

        this.EncuestaRespuesta = new HashSet<EncuestaRespuesta>();

    }


    public int Id { get; set; }

    public int PreguntaID { get; set; }

    public string valor { get; set; }

    public Nullable<int> PesoEstadistico { get; set; }



    public virtual ICollection<EncuestaRespuesta> EncuestaRespuesta { get; set; }

    public virtual Pregunta Pregunta { get; set; }

}

}
