//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestasOrt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pregunta
    {
        public Pregunta()
        {
            this.EncuestaPregunta = new HashSet<EncuestaPregunta>();
            this.EncuestaRespuesta = new HashSet<EncuestaRespuesta>();
            this.Opcion = new HashSet<Opcion>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public bool Requerido { get; set; }
        public Nullable<int> ValorMinimo { get; set; }
        public Nullable<int> ValorMaximo { get; set; }
        public Nullable<int> ValorNormalInicial { get; set; }
        public Nullable<int> ValorNormalFinal { get; set; }
        public Nullable<bool> EstadoInactivo { get; set; }
        public Nullable<bool> Compartir { get; set; }
        public string UsuarioID { get; set; }
        public Nullable<int> TematicaID { get; set; }
        public Nullable<int> MateriaID { get; set; }
    
        public virtual ICollection<EncuestaPregunta> EncuestaPregunta { get; set; }
        public virtual ICollection<EncuestaRespuesta> EncuestaRespuesta { get; set; }
        public virtual ICollection<Opcion> Opcion { get; set; }
        public virtual Materia Materia { get; set; }
        public virtual Tematica Tematica { get; set; }
    }
}
