//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestasOrt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tematica
    {
        public Tematica()
        {
            this.Encuesta = new HashSet<Encuesta>();
            this.Materia = new HashSet<Materia>();
            this.Pregunta = new HashSet<Pregunta>();
        }
    
        public int Id { get; set; }
        public int CarreraID { get; set; }
        public string Descripcion { get; set; }
    
        public virtual Carrera Carrera { get; set; }
        public virtual ICollection<Encuesta> Encuesta { get; set; }
        public virtual ICollection<Materia> Materia { get; set; }
        public virtual ICollection<Pregunta> Pregunta { get; set; }
    }
}
